# Generated by Django 3.0 on 2019-12-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0005_remove_guest_plus_ones'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plus_ones',
            field=models.BooleanField(default=False),
        ),
    ]
