# Generated by Django 3.0 on 2019-12-12 15:48

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address_street', models.TextField()),
                ('address_city', models.CharField(max_length=15)),
                ('address_state', models.CharField(blank=True, max_length=2)),
                ('address_zip', models.CharField(max_length=6)),
                ('address_country', django_countries.fields.CountryField(max_length=2)),
                ('plus_ones', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GuestParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_first_name', models.CharField(max_length=30)),
                ('party_last_name', models.CharField(max_length=30)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Guest')),
            ],
        ),
    ]
