# Generated by Django 3.0 on 2019-12-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='plus_ones',
        ),
    ]
