# Generated by Django 3.0 on 2019-12-12 21:09

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0002_remove_guest_plus_ones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address_state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address_zip',
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
    ]
