# Generated by Django 3.0 on 2019-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0003_auto_20191212_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plus_ones',
            field=models.BooleanField(default=False),
        ),
    ]
