# Generated by Django 3.0 on 2019-12-18 15:31

import RSVP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0008_auto_20191217_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='plus_ones',
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=30, validators=[RSVP.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=30, validators=[RSVP.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='guestparty',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Guest'),
        ),
        migrations.AlterField(
            model_name='guestparty',
            name='party_first_name',
            field=models.CharField(max_length=30, validators=[RSVP.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='guestparty',
            name='party_last_name',
            field=models.CharField(max_length=30, validators=[RSVP.models.validate_name]),
        ),
    ]
